"""Safe deterministic pytest generation from validated replay fixtures."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from phaseprobe import __version__
from phaseprobe.replay import validate_fixture, verify_replay


@dataclass(frozen=True, slots=True)
class GeneratedTest:
    """Generated test, copied fixture, and machine-readable execution evidence."""

    test_path: Path
    fixture_path: Path
    evidence_path: Path


def _safe_name(value: object) -> str:
    candidate = re.sub(r"[^a-z0-9]+", "_", str(value).lower()).strip("_")
    return candidate[:64] or "model"


def _reject_conflict(path: Path, expected: bytes, description: str) -> bool:
    if not path.exists():
        return True
    if not path.is_file() or path.read_bytes() != expected:
        raise FileExistsError(
            f"refusing to overwrite existing {description} {path}; "
            "choose another --output-directory"
        )
    return False


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _classification(payload: object) -> object:
    return payload.get("classification") if isinstance(payload, dict) else None


def generate_regression_test(fixture: Path, output_directory: Path) -> GeneratedTest:
    """Validate evidence, copy its fixture, and emit a non-extensible pytest template."""

    payload = validate_fixture(fixture)
    verification = verify_replay(fixture)
    if not verification.ok:
        raise ValueError(
            "replay fixture does not reproduce; refusing to generate a regression test"
        )
    model_name = _safe_name(payload.get("model"))
    fixture_directory = output_directory / "fixtures"
    copied_fixture = fixture_directory / f"{model_name}-replay.json"
    test_path = output_directory / f"test_{model_name}_transition.py"
    evidence_path = output_directory / f"{model_name}-pytest-evidence.json"
    baseline = payload.get("baseline")
    metadata = baseline.get("execution_metadata") if isinstance(baseline, dict) else None
    adapter_configuration = (
        metadata.get("adapter_configuration") if isinstance(metadata, dict) else None
    )
    scipy_backed = (
        isinstance(adapter_configuration, dict)
        and adapter_configuration.get("adapter") == "scipy.solve_ivp"
    )
    scipy_import = "import pytest\n" if scipy_backed else ""
    scipy_guard = (
        '\npytest.importorskip("scipy")\npytestmark = pytest.mark.scipy\n' if scipy_backed else ""
    )
    source = f'''"""Generated by PhaseProbe from a validated replay fixture."""

from pathlib import Path

{scipy_import}
from phaseprobe.replay import verify_replay
{scipy_guard}

FIXTURE = Path(__file__).parent / "fixtures" / "{model_name}-replay.json"


def test_{model_name}_transition_replays() -> None:
    """Re-execute model/config/seed and verify the fixture's declared replay policy."""
    result = verify_replay(FIXTURE)
    assert result.ok, result.as_dict()
'''
    fixture_bytes = fixture.read_bytes()
    source_bytes = source.encode("utf-8")
    evidence = {
        "schema_version": "1.0",
        "producer": {
            "repository": "aliengineering-byte/phaseprobe",
            "version": __version__,
            "capability": "validated-replay-to-pytest",
            "documentation": "https://github.com/aliengineering-byte/phaseprobe#five-minute-quick-start",
        },
        "claim": {
            "kind": "qualitative-simulation-regression",
            "model": payload.get("model"),
            "baseline_classification": _classification(payload.get("baseline")),
            "changed_classification": _classification(payload.get("changed")),
            "reproducible_at_generation": payload.get("reproducible"),
        },
        "decision": {
            "status": "REPLAY_VERIFIED",
            "comparison_mode": verification.mode,
            "comparisons": [dict(item) for item in verification.comparisons],
        },
        "artifacts": {
            "replay_fixture": {
                "path": copied_fixture.relative_to(output_directory).as_posix(),
                "sha256": _sha256(fixture_bytes),
            },
            "pytest_regression": {
                "path": test_path.relative_to(output_directory).as_posix(),
                "sha256": _sha256(source_bytes),
            },
        },
        "reproduction": {
            "working_directory": ".",
            "command": f"python -m pytest -q {test_path.name}",
        },
        "limitations": [
            "Generation-time replay verifies only the fixture's declared exact or tolerance policy.",
            "The generated pytest detects future mismatch; it does not prove an exact bifurcation point or global minimality.",
        ],
    }
    evidence_bytes = (
        json.dumps(evidence, allow_nan=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    write_fixture = _reject_conflict(copied_fixture, fixture_bytes, "replay fixture")
    write_test = _reject_conflict(test_path, source_bytes, "generated pytest")
    write_evidence = _reject_conflict(evidence_path, evidence_bytes, "generated pytest evidence")
    output_directory.mkdir(parents=True, exist_ok=True)
    fixture_directory.mkdir(exist_ok=True)
    if write_fixture:
        copied_fixture.write_bytes(fixture_bytes)
    if write_test:
        test_path.write_bytes(source_bytes)
    if write_evidence:
        evidence_path.write_bytes(evidence_bytes)
    return GeneratedTest(
        test_path=test_path,
        fixture_path=copied_fixture,
        evidence_path=evidence_path,
    )
