"""Safe deterministic pytest generation from validated replay fixtures."""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from phaseprobe.replay import validate_fixture, verify_replay


@dataclass(frozen=True, slots=True)
class GeneratedTest:
    """Generated fixed-template test and copied integrity-protected fixture."""

    test_path: Path
    fixture_path: Path


def _safe_name(value: object) -> str:
    candidate = re.sub(r"[^a-z0-9]+", "_", str(value).lower()).strip("_")
    return candidate[:64] or "model"


def generate_regression_test(fixture: Path, output_directory: Path) -> GeneratedTest:
    """Validate evidence, copy its fixture, and emit a non-extensible pytest template."""

    payload = validate_fixture(fixture)
    verification = verify_replay(fixture)
    if not verification.ok:
        raise ValueError(
            "replay fixture does not reproduce; refusing to generate a regression test"
        )
    model_name = _safe_name(payload.get("model"))
    output_directory.mkdir(parents=True, exist_ok=True)
    fixture_directory = output_directory / "fixtures"
    fixture_directory.mkdir(exist_ok=True)
    copied_fixture = fixture_directory / f"{model_name}-replay.json"
    shutil.copyfile(fixture, copied_fixture)
    test_path = output_directory / f"test_{model_name}_transition.py"
    source = f'''"""Generated by PhaseProbe from a validated replay fixture."""

from pathlib import Path

from phaseprobe.replay import verify_replay

FIXTURE = Path(__file__).parent / "fixtures" / "{model_name}-replay.json"


def test_{model_name}_transition_replays() -> None:
    """Re-execute model/config/seed and verify class and exact retained trace hashes."""
    result = verify_replay(FIXTURE)
    assert result.ok, result.as_dict()
'''
    test_path.write_text(source, encoding="utf-8", newline="\n")
    return GeneratedTest(test_path=test_path, fixture_path=copied_fixture)
